### ISSUE TITLE
get error when calling on "plot_animation"

### ISSUE THREAD

**Issue by zoucheng1991** [simonalexanderson/StyleGestures#10]
OS: ubuntu 16.04
python: 3.7
pytorch: 1.6.0+cu101
CUDA: 10.1

got the error when calling on plot_animation to generate sample

the saved result in .npz format seems normal

please how to debug~

`generate_sample
writing:results/locomotion/log_20200804_1919/sampled_0_temp100_0k_0.mp4
Traceback (most recent call last):
  File "train_moglow.py", line 61, in <module>
    trainer.generate_sample(eps_std=temp, counter=i)
  File "/home/david/Documents/StyleGestures/glow/trainer.py", line 142, in generate_sample
    self.data.save_animation(control_all[:,:(n_timesteps-n_lookahead),:], sampled_all, os.path.join(self.log_dir, f'sampled_{counter}_temp{str(int(eps_std*100))}_{str(self.global_step//1000)}k'))
  File "/home/david/Documents/StyleGestures/motion/datasets/locomotion.py", line 124, in save_animation
    plot_animation(anim_clip[i,self.seqlen:,:], parents, filename_, fps=self.frame_rate, axis_scale=60)
  File "/home/david/Documents/StyleGestures/visualization/plot_animation.py", line 76, in plot_animation
    ani.save(filename, fps=fps, bitrate=13934)
  File "/home/david/virtualenv/py37/lib/python3.7/site-packages/matplotlib/animation.py", line 1120, in save
    anim._init_draw()  # Clear the initial frame
  File "/home/david/virtualenv/py37/lib/python3.7/site-packages/matplotlib/animation.py", line 1695, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
  File "/home/david/virtualenv/py37/lib/python3.7/site-packages/matplotlib/animation.py", line 1718, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "/home/david/Documents/StyleGestures/visualization/plot_animation.py", line 64, in animate
    [ joints[i,j,1],        joints[i,parents[j],1]])
  File "/home/david/virtualenv/py37/lib/python3.7/site-packages/mpl_toolkits/mplot3d/art3d.py", line 143, in set_3d_properties
    zs = np.broadcast_to(zs, xs.shape)
AttributeError: 'list' object has no attribute 'shape'`

**Comment by simonalexanderson** [comment]
This bug seems to have arisen with an update in matplotlib 3.3. I have fixed the code so it should work now. Please update plot_animation.py.

**Comment by zoucheng1991** [comment]
the update solved the problem
thanks!
